# read_csv()-->
 this function reads the content from the csv files in pandas so that we perform the operation on the dataor we can perform effective analysis

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('youtubechannels.csv')

# dataframe --> 
combination of multiple series (column)

# squeeze -->
 squeeze parameter makes sure that the data is in series format

In [3]:
data=df.squeeze('columns')
type(data)

pandas.DataFrame

In [4]:
dg=pd.read_csv('youtubechannels1.csv').squeeze('columns')

In [5]:
dg

0                      Linus Tech Tips
1                Programming with Mosh
2                           TechSource
3                             Bro Code
4                         John Hammond
                    ...
125         Software Engineering Daily
126            Georgia Web Development
127    Machine Learning and AI Academy
128                 The Helpful Hacker
129            Visual Computer Science
Name: channel_name, Length: 130, dtype: str

In [6]:
type(dg)

pandas.Series

In [7]:
pd.read_csv('youtubechannels2.csv')

                        channel_name  subscribers
0                    Linus Tech Tips     16600000
1              Programming with Mosh      4860000
2                         TechSource      4010000
3                           Bro Code      2990000
4                       John Hammond      2080000
..                               ...          ...
125       Software Engineering Daily        11400
126          Georgia Web Development        11200
127  Machine Learning and AI Academy        11000
128               The Helpful Hacker        10900
129          Visual Computer Science        10800

[130 rows x 2 columns]

In [8]:
## index_col

In [9]:
dataframe=pd.read_csv('youtubechannels2.csv',index_col='channel_name').squeeze('columns')

In [10]:
dataframe

channel_name
Linus Tech Tips                    16600000
Programming with Mosh               4860000
TechSource                          4010000
Bro Code                            2990000
John Hammond                        2080000
                                     ...
Software Engineering Daily            11400
Georgia Web Development               11200
Machine Learning and AI Academy       11000
The Helpful Hacker                    10900
Visual Computer Science               10800
Name: subscribers, Length: 130, dtype: int64

# Atrributes in series
# 1.values -->
representing only the values of the given series.

# 2. index --> 
return only the index values from the given column.

# 3. dtype -->
Dtype provides the idea about the data type of the values that you are storing.

# 4. size -->
this attribute provides the idea about the total number of rows inside the dataset

In [11]:
dg.values

<ArrowStringArray>
[                'Linus Tech Tips',           'Programming with Mosh',
                      'TechSource',                        'Bro Code',
                    'John Hammond',                      'TechLinked',
                'The Coding Train',                 'Paul's Hardware',
                   'Corey Schafer',              'Android Developers',
 ...
                'Tech News Weekly',                 'Web Dev Mastery',
               '🥷 RTP Tech Tips 📡',                'Cloud Simplified',
             'AWS Partner Network',      'Software Engineering Daily',
         'Georgia Web Development', 'Machine Learning and AI Academy',
              'The Helpful Hacker',         'Visual Computer Science']
Length: 130, dtype: str

In [12]:
dataframe.index

Index(['Linus Tech Tips', 'Programming with Mosh', 'TechSource', 'Bro Code',
       'John Hammond', 'TechLinked', 'The Coding Train', 'Paul's Hardware',
       'Corey Schafer', 'Android Developers',
       ...
       'Tech News Weekly', 'Web Dev Mastery', '🥷 RTP Tech Tips 📡',
       'Cloud Simplified', 'AWS Partner Network', 'Software Engineering Daily',
       'Georgia Web Development', 'Machine Learning and AI Academy',
       'The Helpful Hacker', 'Visual Computer Science'],
      dtype='str', name='channel_name', length=130)

In [13]:
dataframe.dtype

dtype('int64')

In [14]:
dataframe.astype('int32')

channel_name
Linus Tech Tips                    16600000
Programming with Mosh               4860000
TechSource                          4010000
Bro Code                            2990000
John Hammond                        2080000
                                     ...
Software Engineering Daily            11400
Georgia Web Development               11200
Machine Learning and AI Academy       11000
The Helpful Hacker                    10900
Visual Computer Science               10800
Name: subscribers, Length: 130, dtype: int32

In [15]:
dataframe.size

130

# shapes -->
this attributes provides the idea about the row column information

In [16]:
dataframe.shape

(130,)

# ndim --> 
this attribute provides the idea about the dimension of the given dataset

In [17]:
dataframe.ndim

1

# name-->
this attributes provides the idea about the name of the series
# is_unique --> 
this providess us with the idea about wheather if unique values are their or not is present in the dataset

In [18]:
dataframe

channel_name
Linus Tech Tips                    16600000
Programming with Mosh               4860000
TechSource                          4010000
Bro Code                            2990000
John Hammond                        2080000
                                     ...
Software Engineering Daily            11400
Georgia Web Development               11200
Machine Learning and AI Academy       11000
The Helpful Hacker                    10900
Visual Computer Science               10800
Name: subscribers, Length: 130, dtype: int64

In [19]:
dataframe.name

'subscribers'

In [20]:
dataframe.is_unique

False

In [21]:
pd.Series([1,2,3,4,5]).is_unique

True

# series methods

# 1. head()-->
provide the top previes of data as the top 5 rows of the dataframe or series. it is quite helpful with providing the preview of the dataset and if we want to preview top 10 rows then we can pass 10 as aargument or for top 7 rows as an argument.

In [22]:
dataframe.head()

channel_name
Linus Tech Tips          16600000
Programming with Mosh     4860000
TechSource                4010000
Bro Code                  2990000
John Hammond              2080000
Name: subscribers, dtype: int64

In [25]:
dataframe.head(5)

channel_name
Linus Tech Tips          16600000
Programming with Mosh     4860000
TechSource                4010000
Bro Code                  2990000
John Hammond              2080000
Name: subscribers, dtype: int64

# tail()->
provides the botton preview of data as the bottom 5 rows. 

eg--> dataset -->salary column -->top 5rows -->salary --> 7 lpa -->top 10-->top 15,,,tail()->
bottom 5 rows-->salary --> 4 lpa,9lpa

# sample() -->
sample() provides any custom row from the dataset for us to preview it

In [32]:
df.sample(5)

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
8,UCCezIgC97PvUuR4_gbFUs5g,Corey Schafer,Welcome to my Channel. This channel is focused...,1490000,105351847,254,2006-05-31T22:49:22Z,US,UUCezIgC97PvUuR4_gbFUs5g,2025-11-20T13:37:53.306286
122,UChVCEXzi39_YEpUQhqmEFrQ,🥷 RTP Tech Tips 📡,🛡️ #FOLLOW 🥷 #Privacy: The ONLY Right Capable ...,14200,1257653,395,2018-09-14T04:33:54Z,US,UUhVCEXzi39_YEpUQhqmEFrQ,2025-11-20T13:37:53.306286
49,UCMLtBahI5DMrt0NPvDSoIRQ,Machine Learning Street Talk,MLST is the top technical AI podcast on Spotif...,204000,11577426,310,2020-04-09T18:54:44.486149Z,GB,UUMLtBahI5DMrt0NPvDSoIRQ,2025-11-20T13:37:53.306286
89,UCGgAsNJ-w5v4c4iyOH_hGig,Learn Computer Science,Learn Computer science online is an educationa...,46900,2916967,43,2019-06-07T06:53:05Z,IN,UUGgAsNJ-w5v4c4iyOH_hGig,2025-11-20T13:37:53.306286
29,UC0Q7Hlz75NYhYAuq6O0fqHw,Jeremy's IT Lab,This channel is for people looking to learn ab...,512000,51866901,321,2019-04-21T03:33:14Z,JP,UU0Q7Hlz75NYhYAuq6O0fqHw,2025-11-20T13:37:53.306286

# value_counts() -->
 it provides the idea about the count of the values(categeorical value) if i am having a column where the categorical value count i wnat to calculate then i can go with value_counts()

In [42]:
df.tail(10)

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
120,UCfSgan80IQD_5U1t7UuwL3w,Tech News Weekly,"Industry expert Mikah Sargent, brings you inte...",15200,429984,414,2014-02-26T20:51:43Z,US,UUfSgan80IQD_5U1t7UuwL3w,2025-11-20T13:37:53.306286
121,UCQVE2WU-h_dszY5If6oFvFg,Web Dev Mastery,🚀 Welcome to Web Dev Mastery \n\nJourney into ...,15100,1036647,256,2023-02-20T14:50:56.839366Z,IN,UUQVE2WU-h_dszY5If6oFvFg,2025-11-20T13:37:53.306286
122,UChVCEXzi39_YEpUQhqmEFrQ,🥷 RTP Tech Tips 📡,🛡️ #FOLLOW 🥷 #Privacy: The ONLY Right Capable ...,14200,1257653,395,2018-09-14T04:33:54Z,US,UUhVCEXzi39_YEpUQhqmEFrQ,2025-11-20T13:37:53.306286
123,UCA7HuPQ_JRBi7KN8muvxc2w,Cloud Simplified,"Demystifying Cloud Computing, making it access...",13300,592201,122,2008-05-19T15:25:57Z,NaN,UUA7HuPQ_JRBi7KN8muvxc2w,2025-11-20T13:37:53.306286
124,UC5jiGyfEcnFJNjtyS40c3Zg,AWS Partner Network,The AWS Partner Network (APN) is the global co...,12100,279783,545,2018-08-13T20:46:07Z,US,UU5jiGyfEcnFJNjtyS40c3Zg,2025-11-20T13:37:53.306286
125,UCBKM3HATRILZyG9jGNJKGXQ,Software Engineering Daily,The world through the lens of software. \n\n🎙️...,11400,302138,1138,2017-05-19T21:45:38Z,US,UUBKM3HATRILZyG9jGNJKGXQ,2025-11-20T13:37:53.306286
126,UCvckuc-3Sos1aUtSqCV_0xw,Georgia Web Development,"Georgia Web Development is a Moultrie, Georgia...",11200,6878757,212,2014-03-17T20:28:26Z,US,UUvckuc-3Sos1aUtSqCV_0xw,2025-11-20T13:37:53.306286
127,UC4lM4hz_v5ixNjK54UwPEVw,Machine Learning and AI Academy,"Welcome to Machine Learning and AI Academy, yo...",11000,130381,60,2019-12-26T13:37:41.612225Z,GB,UU4lM4hz_v5ixNjK54UwPEVw,2025-11-20T13:37:53.306286
128,UCTnOFmMwZIi7jJYS_nAfeyQ,The Helpful Hacker,Welcome to The Helpful Hacker! I’m a passionat...,10900,587499,64,2024-06-17T17:08:58.598812Z,US,UUTnOFmMwZIi7jJYS_nAfeyQ,2025-11-20T13:37:53.306286
129,UCHd1qamEkVSlTWkEqIqJbEQ,Visual Computer Science,Welcome to Visual Computer Science! This chann...,10800,839331,35,2020-06-07T09:55:36.218375Z,US,UUHd1qamEkVSlTWkEqIqJbEQ,2025-11-20T13:37:53.306286

In [35]:
youtube=pd.read_csv('youtubechannels.csv')

In [36]:
youtube

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
0,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,"Linus Tech Tips is a passionate team of ""profe...",16600000,9092244390,6989,2008-11-25T00:46:52Z,CA,UUXuqSBlHAE6Xw-yeJA0Tunw,2025-11-20T13:37:53.306286
1,UCWv7vMbMWH4-V0ZXdmDpPBA,Programming with Mosh,"Hi! I'm Mosh 👋, a software engineer with over ...",4860000,257598451,243,2014-10-07T00:40:53Z,US,UUWv7vMbMWH4-V0ZXdmDpPBA,2025-11-20T13:37:53.306286
2,UChIZGfcnjHI0DG4nweWEduw,TechSource,Join the Discord Server:\nhttps://discord.gg/T...,4010000,870967915,1897,2010-01-24T22:34:11Z,US,UUhIZGfcnjHI0DG4nweWEduw,2025-11-20T13:37:53.306286
3,UC4SVo0Ue36XCfOyb5Lh1viQ,Bro Code,Coding bootcamps HATE HIM! 🗿\n,2990000,178609297,1000,2019-10-10T14:40:46.568078Z,US,UU4SVo0Ue36XCfOyb5Lh1viQ,2025-11-20T13:37:53.306286
4,UCVeW9qkBjo3zosnqUbG7CFw,John Hammond,Free Cybersecurity Education and Ethical Hacking.,2080000,82120292,1740,2011-02-06T03:59:46Z,US,UUVeW9qkBjo3zosnqUbG7CFw,2025-11-20T13:37:53.306286
...,...,...,...,...,...,...,...,...,...,...
125,UCBKM3HATRILZyG9jGNJKGXQ,Software Engineering Daily,The world through the lens of software. \n\n🎙️...,11400,302138,1138,2017-05-19T21:45:38Z,US,UUBKM3HATRILZyG9jGNJKGXQ,2025-11-20T13:37:53.306286
126,UCvckuc-3Sos1aUtSqCV_0xw,Georgia Web Development,"Georgia Web Development is a Moultrie, Georgia...",11200,6878757,212,2014-03-17T20:28:26Z,US,UUvckuc-3Sos1aUtSqCV_0xw,2025-11-20T13:37:53.306286
127,UC4lM4hz_v5ixNjK54UwPEVw,Machine Learning and AI Academy,"Welcome to Machine Learning and AI Academy, yo...",11000,130381,60,2019-12-26T13:37:41.612225Z,GB,UU4lM4hz_v5ixNjK54UwPEVw,2025-11-20T13:37:53.306286
128,UCTnOFmMwZIi7jJYS_nAfeyQ,The Helpful Hacker,Welcome to The Helpful Hacker! I’m a passionat...,10900,587499,64,2024-06-17T17:08:58.598812Z,US,UUTnOFmMwZIi7jJYS_nAfeyQ,2025-11-20T13:37:53.306286
129,UCHd1qamEkVSlTWkEqIqJbEQ,Visual Computer Science,Welcome to Visual Computer Science! This chann...,10800,839331,35,2020-06-07T09:55:36.218375Z,US,UUHd1qamEkVSlTWkEqIqJbEQ,2025-11-20T13:37:53.306286

In [38]:
avg=youtube['total_videos']

In [39]:
avg

0      6989
1       243
2      1897
3      1000
4      1740
       ...
125    1138
126     212
127      60
128      64
129      35
Name: total_videos, Length: 130, dtype: int64

In [40]:
type(avg)

pandas.Series

In [ ]:
# isme kitna value same hai ye count karta hai
avg.value_counts()

total_videos
186     2
105     2
520     2
362     2
256     2
       ..
1138    1
212     1
60      1
64      1
35      1
Name: count, Length: 120, dtype: int64

# sort_values()-->
this method sorts the value in an ascending manner. it can be usefull for us for the numerical  columns.you can even sort value in descending manner as well.

In [43]:
avg.sort_values()

106       13
66        13
83        33
129       35
21        36
       ...
105     5108
0       6989
57     11530
22     13014
18     18375
Name: total_videos, Length: 130, dtype: int64

In [44]:
avg.sort_values(ascending=False)

18     18375
22     13014
57     11530
0       6989
105     5108
       ...
21        36
129       35
83        33
66        13
106       13
Name: total_videos, Length: 130, dtype: int64

# method chaining --> 
we will use multiple methods together to get required value in a way the first method's output will be second method imput then 2nd method output will be 3rd method input

In [45]:
avg.sort_values(ascending=False).head(1)

18    18375
Name: total_videos, dtype: int64

In [48]:
avg.sort_values(ascending=True).tail(1).values[0]

np.int64(18375)

# inlace-->
norder to make a change in our data permanent .

In [49]:
average_data=avg.copy()

In [50]:
average_data

0      6989
1       243
2      1897
3      1000
4      1740
       ...
125    1138
126     212
127      60
128      64
129      35
Name: total_videos, Length: 130, dtype: int64

In [51]:
average_data.sort_values(inplace=True)

In [52]:
average_data

106       13
66        13
83        33
129       35
21        36
       ...
105     5108
0       6989
57     11530
22     13014
18     18375
Name: total_videos, Length: 130, dtype: int64

## sort_index()-->
 this method sorts the index of the dataset.

In [ ]:
# dataframe working
# machinelearning cycle --> data gathering(storing it into a dataframe)-->data exploration -->exploratory data analysis(pandas, matplotlib,seaborn)-->data preprocessing --> machine learning models

# for reading the content from a tabular data or the data that is stored in a2d structure or in rows and columns format or consisting of multipla series in combination we require dataframe and on the pab=ndas dataframe we can have the functions to explore and to perform manipulation and analysis on the data we are going to store inside it.