In [1]:
import pandas as pd

In [2]:
youtube=pd.read_csv("youtube.csv")

In [3]:
youtube

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
0,T-Series,Yes,249.0,Hindi[7][8],Music,India
1,MrBeast,No,184.0,English,Entertainment,United States
2,Cocomelon,Yes,165.0,English,Education,United States
3,Sony Entertainment Television India,Yes,162.0,Hindi[9],Entertainment,India
4,Kids Diana Show,Yes,113.0,English[10][11][12],Entertainment,Ukraine- United States
5,PewDiePie,No,111.0,English,Entertainment,Sweden
6,Like Nastya,No,107.0,English,Entertainment,Russia- United States
7,Vlad and Niki,No,101.0,English,Entertainment,Russia- United States
8,Zee Music Company,Yes,99.5,Hindi[13][14],Music,India
9,WWE,Yes,97.1,English,Sports,United States
10,Blackpink,No,91.2,Korean,Music,South Korea
11,Goldmines,Yes,89.5,Hindi,Film,India
12,Sony SAB,Yes,85.2,Hindi,Entertainment,India
13,5-Minute Crafts,Yes,80.2,English,How-to,Cyprus[a]
14,BangtanTV,No,76.4,Korean,Music,South Korea
15,Hybe Labels,Yes,72.6,Korean,Music,South Korea
16,Zee TV,Yes,72.4,Hindi,Entertainment,India
17,Justin Bieber,No,71.9,English,Music,Canada
18,Pinkfong,Yes,69.5,English,Education,South Korea
19,ChuChu TV Nursery Rhymes & Kids Songs,Yes,67.5,Hindi[16],Education,India
20,Canal KondZilla,Yes,66.6,Portuguese,Music,Brazil
21,Colors TV,Yes,66.6,Hindi,Entertainment,India
22,Shemaroo Entertainment,Yes,66.3,Hindi,Music,India
23,T-Series Bhakti Sagar,Yes,62.4,Hindi,Music,India
24,Tips Official,Yes,60.8,Hindi,Entertainment,India
25,Movieclips,Yes,59.8,English,Film,United States
26,Dude Perfect,No,59.7,English,Sports,United States
27,El Reino Infantil,Yes,59.7,Spanish,Music,Argentina
28,Aaj Tak,Yes,58.8,Hindi,News,India
29,Wave Music,Yes,58.7,Bhojpuri,Music,India
30,Sony Music India,Yes,57.8,Hindi,Music,India
31,Eminem,No,57.4,English,Music,United States
32,Marshmello,No,56.5,English,Music,United States
33,Yash Raj Films,Yes,55.7,Hindi,Music,India
34,Infobells,Yes,55.6,Hindi,Education,India
35,LooLoo Kids,Yes,54.7,English,Music,Romania
36,Taylor Swift,No,54.1,English,Music,United States
37,Ed Sheeran,No,53.7,English,Music,United Kingdom
38,BillionSurpriseToys,Yes,53.0,English,Entertainment,United States
39,Ariana Grande,No,52.9,English,Music,United States
40,Shemaroo,Yes,48.8,Hindi,Entertainment,India
41,JuegaGerman,No,48.6,Spanish,Entertainment,Chile
42,Billie Eilish,No,48.5,English,Music,United States
43,Get Movies,Yes,48.1,Russian,Entertainment,Russia
44,SonyMusicIndiaVEVO,Yes,47.4,Hindi,Music,India
45,A4,No,47.2,Russian,Entertainment,Belarus
46,Badabun,Yes,47.0,Spanish,Entertainment,Mexico
47,Bad Bunny,No,46.4,Spanish,Music,United States ( Puerto Rico)
48,Har Pal Geo,Yes,46.3,Urdu,Entertainment,Pakistan
49,Fernanfloo,No,46.3,Spanish,Games,El Salvador

In [6]:
sub=youtube['Subscribers (millions)']

In [7]:
sub

0     249.0
1     184.0
2     165.0
3     162.0
4     113.0
5     111.0
6     107.0
7     101.0
8      99.5
9      97.1
10     91.2
11     89.5
12     85.2
13     80.2
14     76.4
15     72.6
16     72.4
17     71.9
18     69.5
19     67.5
20     66.6
21     66.6
22     66.3
23     62.4
24     60.8
25     59.8
26     59.7
27     59.7
28     58.8
29     58.7
30     57.8
31     57.4
32     56.5
33     55.7
34     55.6
35     54.7
36     54.1
37     53.7
38     53.0
39     52.9
40     48.8
41     48.6
42     48.5
43     48.1
44     47.4
45     47.2
46     47.0
47     46.4
48     46.3
49     46.3
Name: Subscribers (millions), dtype: float64

# mathematical function in pandas 
# 1.sum()-->
 sum of all value present in the series
 ## 2. product()-->
 product of all values in the series
 # 3.mean()--> 
 mean provides us with the average value of the data column
 # for eg--> company data -->salary --> average value for that column salary=7,6,8,9,11 
 mean=(7+6+8+9+11)/5-->8 LPA

 # median() -->
 median also provides the idea about the average of the the data.for coming up with median, we need to sort the value in ascending manner and then the middle value after sorting the data -->median ;
 data --->salary-->1 crore (outlier)-->avg-->7+6+8+9+11

# mode()-->
mode provides us with the idea that which value is getting repeated maximum number of times. 

# std()-->
if i need to get the idea that how the value inside the series are distributed from the average or mean value then we come up with thes stabdaer deviation.

# salary--->
 7,8,6,6.5,7.5 -->low standard deviation

# salary -->
 7,15,4,20,28,17 -->high standard diveation

# variance--> 
varience also provides the insight about the distribution of the data dfrom the mean value and variance is the square of standar derivation.
# standard_deviation=|mean=v_1|+|mean-v_2|....../total count of values

# variance=std**2

# min()->
mainimum value in the series
# max()--->
maximum value in the series

# describe() -->
 describe fn provides the idea about the summmary of the important mathematical calculation for the data

min-->minimum value

max--> maximum value

mean --> average value

std --> standard derivation

25%--->25% of the values out my all values are less than this specific value \

50%--->50% of the values out my all values are less than this specific value 

75%--->75% of the values out my all values are less than this specific value 

# JEE MAINS-->25% --> my score in jee mains was greater than 25% of the total applicants who applied in jee

In [28]:
average

0    46.3
1    59.7
2    66.6
Name: Subscribers (millions), dtype: float64

In [8]:
sub.sum()

np.float64(3810.4)

In [9]:
sub.product()

np.float64(1.4884969316571977e+92)

In [12]:
sub.sort_values()

48     46.3
49     46.3
47     46.4
46     47.0
45     47.2
44     47.4
43     48.1
42     48.5
41     48.6
40     48.8
39     52.9
38     53.0
37     53.7
36     54.1
35     54.7
34     55.6
33     55.7
32     56.5
31     57.4
30     57.8
29     58.7
28     58.8
26     59.7
27     59.7
25     59.8
24     60.8
23     62.4
22     66.3
20     66.6
21     66.6
19     67.5
18     69.5
17     71.9
16     72.4
15     72.6
14     76.4
13     80.2
12     85.2
11     89.5
10     91.2
9      97.1
8      99.5
7     101.0
6     107.0
5     111.0
4     113.0
3     162.0
2     165.0
1     184.0
0     249.0
Name: Subscribers (millions), dtype: float64

In [13]:
sub.mean

<bound method Series.mean of 0     249.0
1     184.0
2     165.0
3     162.0
4     113.0
5     111.0
6     107.0
7     101.0
8      99.5
9      97.1
10     91.2
11     89.5
12     85.2
13     80.2
14     76.4
15     72.6
16     72.4
17     71.9
18     69.5
19     67.5
20     66.6
21     66.6
22     66.3
23     62.4
24     60.8
25     59.8
26     59.7
27     59.7
28     58.8
29     58.7
30     57.8
31     57.4
32     56.5
33     55.7
34     55.6
35     54.7
36     54.1
37     53.7
38     53.0
39     52.9
40     48.8
41     48.6
42     48.5
43     48.1
44     47.4
45     47.2
46     47.0
47     46.4
48     46.3
49     46.3
Name: Subscribers (millions), dtype: float64>

In [14]:
sub.median()

np.float64(60.3)

In [27]:
sub.mode()

0    46.3
1    59.7
2    66.6
Name: Subscribers (millions), dtype: float64

In [33]:
sub.mode()

0    46.3
1    59.7
2    66.6
Name: Subscribers (millions), dtype: float64

In [32]:
sub.std()

np.float64(39.73522490132884)

In [39]:
youtube.max()

Name                                            Zee TV
Brand channel                                      Yes
Subscribers (millions)                           249.0
Primary language                                  Urdu
Category                                        Sports
Country                   United States ( Puerto Rico)
dtype: object

In [40]:
youtube.min()

Name                      5-Minute Crafts
Brand channel                          No
Subscribers (millions)               46.3
Primary language                 Bhojpuri
Category                        Education
Country                         Argentina
dtype: object

In [41]:
sub.describe()

count     50.000000
mean      76.208000
std       39.735225
min       46.300000
25%       53.800000
50%       60.300000
75%       83.950000
max      249.000000
Name: Subscribers (millions), dtype: float64

# Indexing in series( to have the access over the certain value or values)

--> 1. positive Indexing(just like list)--->
start from 0 to forward  direction

--> 2.no negative Indexing is allowed

--> 3. slicing --> in series we can get the certain values over a given specific range and we can do it using [initial_value,final_value+1,gapof interval]

--> 4. fancy Indexing ---> if i wnat the specific values from the series then we can go with fancy indexing.

-->5.Indexing with labels -->A  series which is consisting of labels as the index or custom index, then for this data we can retrieve the
info using that custom index or label

In [42]:
sub[0]

np.float64(249.0)

In [43]:
sub[7]

np.float64(101.0)

In [ ]:
# slicing concept
sub[7:17]

7     101.0
8      99.5
9      97.1
10     91.2
11     89.5
12     85.2
13     80.2
14     76.4
15     72.6
16     72.4
Name: Subscribers (millions), dtype: float64

In [47]:
# if i want the values skipped as a certain value
sub[2:15:2]

2     165.0
4     113.0
6     107.0
8      99.5
10     91.2
12     85.2
14     76.4
Name: Subscribers (millions), dtype: float64

In [49]:
# reverse values in a series
sub[::-1]

49     46.3
48     46.3
47     46.4
46     47.0
45     47.2
44     47.4
43     48.1
42     48.5
41     48.6
40     48.8
39     52.9
38     53.0
37     53.7
36     54.1
35     54.7
34     55.6
33     55.7
32     56.5
31     57.4
30     57.8
29     58.7
28     58.8
27     59.7
26     59.7
25     59.8
24     60.8
23     62.4
22     66.3
21     66.6
20     66.6
19     67.5
18     69.5
17     71.9
16     72.4
15     72.6
14     76.4
13     80.2
12     85.2
11     89.5
10     91.2
9      97.1
8      99.5
7     101.0
6     107.0
5     111.0
4     113.0
3     162.0
2     165.0
1     184.0
0     249.0
Name: Subscribers (millions), dtype: float64

In [ ]:
# fancing indexing
sub[[2,4,9,15]]

2     165.0
4     113.0
9      97.1
15     72.6
Name: Subscribers (millions), dtype: float64

In [54]:
sub[[34,12,24,28]]

34    55.6
12    85.2
24    60.8
28    58.8
Name: Subscribers (millions), dtype: float64

In [70]:
df=youtube

In [71]:
df

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
0,T-Series,Yes,249.0,Hindi[7][8],Music,India
1,MrBeast,No,184.0,English,Entertainment,United States
2,Cocomelon,Yes,165.0,English,Education,United States
3,Sony Entertainment Television India,Yes,162.0,Hindi[9],Entertainment,India
4,Kids Diana Show,Yes,113.0,English[10][11][12],Entertainment,Ukraine- United States
5,PewDiePie,No,111.0,English,Entertainment,Sweden
6,Like Nastya,No,107.0,English,Entertainment,Russia- United States
7,Vlad and Niki,No,101.0,English,Entertainment,Russia- United States
8,Zee Music Company,Yes,99.5,Hindi[13][14],Music,India
9,WWE,Yes,97.1,English,Sports,United States
10,Blackpink,No,91.2,Korean,Music,South Korea
11,Goldmines,Yes,89.5,Hindi,Film,India
12,Sony SAB,Yes,85.2,Hindi,Entertainment,India
13,5-Minute Crafts,Yes,80.2,English,How-to,Cyprus[a]
14,BangtanTV,No,76.4,Korean,Music,South Korea
15,Hybe Labels,Yes,72.6,Korean,Music,South Korea
16,Zee TV,Yes,72.4,Hindi,Entertainment,India
17,Justin Bieber,No,71.9,English,Music,Canada
18,Pinkfong,Yes,69.5,English,Education,South Korea
19,ChuChu TV Nursery Rhymes & Kids Songs,Yes,67.5,Hindi[16],Education,India
20,Canal KondZilla,Yes,66.6,Portuguese,Music,Brazil
21,Colors TV,Yes,66.6,Hindi,Entertainment,India
22,Shemaroo Entertainment,Yes,66.3,Hindi,Music,India
23,T-Series Bhakti Sagar,Yes,62.4,Hindi,Music,India
24,Tips Official,Yes,60.8,Hindi,Entertainment,India
25,Movieclips,Yes,59.8,English,Film,United States
26,Dude Perfect,No,59.7,English,Sports,United States
27,El Reino Infantil,Yes,59.7,Spanish,Music,Argentina
28,Aaj Tak,Yes,58.8,Hindi,News,India
29,Wave Music,Yes,58.7,Bhojpuri,Music,India
30,Sony Music India,Yes,57.8,Hindi,Music,India
31,Eminem,No,57.4,English,Music,United States
32,Marshmello,No,56.5,English,Music,United States
33,Yash Raj Films,Yes,55.7,Hindi,Music,India
34,Infobells,Yes,55.6,Hindi,Education,India
35,LooLoo Kids,Yes,54.7,English,Music,Romania
36,Taylor Swift,No,54.1,English,Music,United States
37,Ed Sheeran,No,53.7,English,Music,United Kingdom
38,BillionSurpriseToys,Yes,53.0,English,Entertainment,United States
39,Ariana Grande,No,52.9,English,Music,United States
40,Shemaroo,Yes,48.8,Hindi,Entertainment,India
41,JuegaGerman,No,48.6,Spanish,Entertainment,Chile
42,Billie Eilish,No,48.5,English,Music,United States
43,Get Movies,Yes,48.1,Russian,Entertainment,Russia
44,SonyMusicIndiaVEVO,Yes,47.4,Hindi,Music,India
45,A4,No,47.2,Russian,Entertainment,Belarus
46,Badabun,Yes,47.0,Spanish,Entertainment,Mexico
47,Bad Bunny,No,46.4,Spanish,Music,United States ( Puerto Rico)
48,Har Pal Geo,Yes,46.3,Urdu,Entertainment,Pakistan
49,Fernanfloo,No,46.3,Spanish,Games,El Salvador

In [ ]:

dataframe

In [78]:
df['T-Series']

KeyError: 'T-Series'

# editing series(bring the changes into the values stored inside the series)

1.using Indexing --> df[0]=65--> changing the original value at index 0 to 65

In [80]:
df=pd.DataFrame(youtube)

In [81]:
df

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
0,T-Series,Yes,249.0,Hindi[7][8],Music,India
1,MrBeast,No,184.0,English,Entertainment,United States
2,Cocomelon,Yes,165.0,English,Education,United States
3,Sony Entertainment Television India,Yes,162.0,Hindi[9],Entertainment,India
4,Kids Diana Show,Yes,113.0,English[10][11][12],Entertainment,Ukraine- United States
5,PewDiePie,No,111.0,English,Entertainment,Sweden
6,Like Nastya,No,107.0,English,Entertainment,Russia- United States
7,Vlad and Niki,No,101.0,English,Entertainment,Russia- United States
8,Zee Music Company,Yes,99.5,Hindi[13][14],Music,India
9,WWE,Yes,97.1,English,Sports,United States
10,Blackpink,No,91.2,Korean,Music,South Korea
11,Goldmines,Yes,89.5,Hindi,Film,India
12,Sony SAB,Yes,85.2,Hindi,Entertainment,India
13,5-Minute Crafts,Yes,80.2,English,How-to,Cyprus[a]
14,BangtanTV,No,76.4,Korean,Music,South Korea
15,Hybe Labels,Yes,72.6,Korean,Music,South Korea
16,Zee TV,Yes,72.4,Hindi,Entertainment,India
17,Justin Bieber,No,71.9,English,Music,Canada
18,Pinkfong,Yes,69.5,English,Education,South Korea
19,ChuChu TV Nursery Rhymes & Kids Songs,Yes,67.5,Hindi[16],Education,India
20,Canal KondZilla,Yes,66.6,Portuguese,Music,Brazil
21,Colors TV,Yes,66.6,Hindi,Entertainment,India
22,Shemaroo Entertainment,Yes,66.3,Hindi,Music,India
23,T-Series Bhakti Sagar,Yes,62.4,Hindi,Music,India
24,Tips Official,Yes,60.8,Hindi,Entertainment,India
25,Movieclips,Yes,59.8,English,Film,United States
26,Dude Perfect,No,59.7,English,Sports,United States
27,El Reino Infantil,Yes,59.7,Spanish,Music,Argentina
28,Aaj Tak,Yes,58.8,Hindi,News,India
29,Wave Music,Yes,58.7,Bhojpuri,Music,India
30,Sony Music India,Yes,57.8,Hindi,Music,India
31,Eminem,No,57.4,English,Music,United States
32,Marshmello,No,56.5,English,Music,United States
33,Yash Raj Films,Yes,55.7,Hindi,Music,India
34,Infobells,Yes,55.6,Hindi,Education,India
35,LooLoo Kids,Yes,54.7,English,Music,Romania
36,Taylor Swift,No,54.1,English,Music,United States
37,Ed Sheeran,No,53.7,English,Music,United Kingdom
38,BillionSurpriseToys,Yes,53.0,English,Entertainment,United States
39,Ariana Grande,No,52.9,English,Music,United States
40,Shemaroo,Yes,48.8,Hindi,Entertainment,India
41,JuegaGerman,No,48.6,Spanish,Entertainment,Chile
42,Billie Eilish,No,48.5,English,Music,United States
43,Get Movies,Yes,48.1,Russian,Entertainment,Russia
44,SonyMusicIndiaVEVO,Yes,47.4,Hindi,Music,India
45,A4,No,47.2,Russian,Entertainment,Belarus
46,Badabun,Yes,47.0,Spanish,Entertainment,Mexico
47,Bad Bunny,No,46.4,Spanish,Music,United States ( Puerto Rico)
48,Har Pal Geo,Yes,46.3,Urdu,Entertainment,Pakistan
49,Fernanfloo,No,46.3,Spanish,Games,El Salvador

In [84]:
df[df["Name"]=="T-Series"]

,Name,Brand channel,Subscribers (millions),Primary language,Category,Country
0,T-Series,Yes,249.0,Hindi[7][8],Music,India

In [87]:
from pandas import DataFrame
df=DataFrame

In [90]:
df.describe('T-Series')

AttributeError: 'str' object has no attribute 'ndim'

In [ ]:
## slicing in series --> df[2:7]=100 -->100 vlaue will be  associated for index 2 to 6

In [92]:
sub[1:7]=28

In [93]:
sub

0     249.0
1      28.0
2      28.0
3      28.0
4      28.0
5      28.0
6      28.0
7     101.0
8      99.5
9      97.1
10     91.2
11     89.5
12     85.2
13     80.2
14     76.4
15     72.6
16     72.4
17     71.9
18     69.5
19     67.5
20     66.6
21     66.6
22     66.3
23     62.4
24     60.8
25     59.8
26     59.7
27     59.7
28     58.8
29     58.7
30     57.8
31     57.4
32     56.5
33     55.7
34     55.6
35     54.7
36     54.1
37     53.7
38     53.0
39     52.9
40     48.8
41     48.6
42     48.5
43     48.1
44     47.4
45     47.2
46     47.0
47     46.4
48     46.3
49     46.3
Name: Subscribers (millions), dtype: float64

In [94]:
# fancy indexing --> df[2,4,8]=45,84,79

In [97]:
sub[[0,17,23,40]]=[23,12,17,29]

In [98]:
sub

0      23.0
1      28.0
2      28.0
3      28.0
4      28.0
5      28.0
6      28.0
7     101.0
8      99.5
9      97.1
10     91.2
11     89.5
12     85.2
13     80.2
14     76.4
15     72.6
16     72.4
17     12.0
18     69.5
19     67.5
20     66.6
21     66.6
22     66.3
23     17.0
24     60.8
25     59.8
26     59.7
27     59.7
28     58.8
29     58.7
30     57.8
31     57.4
32     56.5
33     55.7
34     55.6
35     54.7
36     54.1
37     53.7
38     53.0
39     52.9
40     29.0
41     48.6
42     48.5
43     48.1
44     47.4
45     47.2
46     47.0
47     46.4
48     46.3
49     46.3
Name: Subscribers (millions), dtype: float64

In [ ]:
# index labelling
'''dataframe set nahi hai isliye array aa raha hai but syntax sahi hai'''
dataframe[['T_Serires','Shemaroo']]=[34,45]

TypeError: 'method' object does not support item assignment